version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    groups:
      all:
        patterns:
          - "*"
  - package-ecosystem: pip
    directory: /
    schedule:
      interval: weekly
    groups:
      all:
        patterns:
          - "*"
    ignore:
      # For now, we use dependabot to notify us only about major library updates
      - dependency-name: "*"
        update-types:
          - "version-update:semver-patch"
          - "version-update:semver-minor"
